### PR TITLE
Mastery Exercise

### PR DESCRIPTION
**Pull request by jaredshane**
Whoops, was working on master branch on accident so it closed my previous pull request.

### CODE REVIEW

**Comment by dmserrano** [comment]
Great job! Very clean code. 👍 

Nice touch with figuring out you can listen for the form submission.

**Comment by dmserrano** [comment]
^ That means you can merge btw

**Comment by jaredshane** [comment]
@DominicSerranoC14 thanks! appreciate it!

**Comment by jaredshane** [comment]
@DominicSerranoC14 from here on, if I feel like just making cosmetic changes and tweaking a few things (e.g. I want to figure out how to not have `console.log("Merry Christmas")` show up whenever the alert box pops up), should I get approval from one of you all before I push to master or am I good to push up whenever I feel necessary now?

**Comment by dmserrano** [comment]
Sorry, just now saw this. Once one of us gives you a thumbs up, the repo is yours.

**Pull request merged**
